namespace ClanNewsTool
{
    public static class Localization
    {
        private static Dictionary<string, string> _strings = new();

        public static string CurrentLanguage { get; private set; } = "de";

        private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
        {
            ["de"] = new()
            {
                ["app_title"] = "Clan News Tool – Wolffiles.eu",
                ["login"] = "Einloggen",
                ["logout"] = "Ausloggen",
                ["update"] = "🔄 Update",
                ["api_key"] = "API Key:",
                ["api_key_hint"] = "API Key eingeben...",
                ["connecting"] = "Verbinde...",
                ["invalid_key"] = "Ungültiger API Key!",
                ["connection_error"] = "Verbindung fehlgeschlagen!",
                ["enter_key"] = "Bitte API Key eingeben!",
                ["subtitle"] = "Wolffiles.eu – Clan Portal",
                ["tab_news"] = "📰 News",
                ["tab_event"] = "📅 Event",
                ["tab_match"] = "⚔️ Match",
                ["tab_recruit"] = "🎮 Rekrutierung",
                ["title"] = "Titel *",
                ["excerpt"] = "Kurzbeschreibung (optional)",
                ["content_news"] = "Inhalt *",
                ["content_event"] = "Beschreibung *",
                ["content_match"] = "Match-Bericht *",
                ["content_recruit"] = "Anforderungen & Details *",
                ["event_date"] = "Datum & Uhrzeit *",
                ["event_location"] = "Ort / Server (optional)",
                ["opponent"] = "Gegner-Clan *",
                ["result"] = "Ergebnis (z.B. 2:1)",
                ["map"] = "Map (optional)",
                ["match_date"] = "Match-Datum",
                ["btn_news"] = "📰 News posten",
                ["btn_event"] = "📅 Event posten",
                ["btn_match"] = "⚔️ Match posten",
                ["btn_recruit"] = "🎮 Rekrutierung posten",
                ["success"] = "✅ Erfolgreich – wartet auf Freischaltung!",
                ["error_prefix"] = "❌ Fehler: ",
                ["conn_error"] = "❌ Verbindungsfehler: ",
                ["fill_required"] = "Bitte alle Pflichtfelder (*) ausfüllen!",
                ["enter_opponent"] = "Bitte Gegner-Clan eingeben!",
                ["unknown_error"] = "Unbekannter Fehler",
                ["update_available"] = "Update verfügbar",
                ["update_msg"] = "Neue Version verfügbar: {0}\nAktuelle Version: {1}\n\nÄnderungen:\n{2}\n\nJetzt aktualisieren?",
                ["no_update"] = "Du hast bereits die neueste Version!",
                ["no_update_title"] = "Kein Update",
                ["downloading"] = "Update wird heruntergeladen...",
                ["update_failed"] = "Update fehlgeschlagen: ",
            },
            ["en"] = new()
            {
                ["app_title"] = "Clan News Tool – Wolffiles.eu",
                ["login"] = "Login",
                ["logout"] = "Logout",
                ["update"] = "🔄 Update",
                ["api_key"] = "API Key:",
                ["api_key_hint"] = "Enter API Key...",
                ["connecting"] = "Connecting...",
                ["invalid_key"] = "Invalid API Key!",
                ["connection_error"] = "Connection failed!",
                ["enter_key"] = "Please enter your API Key!",
                ["subtitle"] = "Wolffiles.eu – Clan Portal",
                ["tab_news"] = "📰 News",
                ["tab_event"] = "📅 Event",
                ["tab_match"] = "⚔️ Match",
                ["tab_recruit"] = "🎮 Recruitment",
                ["title"] = "Title *",
                ["excerpt"] = "Short description (optional)",
                ["content_news"] = "Content *",
                ["content_event"] = "Description *",
                ["content_match"] = "Match Report *",
                ["content_recruit"] = "Requirements & Details *",
                ["event_date"] = "Date & Time *",
                ["event_location"] = "Location / Server (optional)",
                ["opponent"] = "Opponent Clan *",
                ["result"] = "Result (e.g. 2:1)",
                ["map"] = "Map (optional)",
                ["match_date"] = "Match Date",
                ["btn_news"] = "📰 Post News",
                ["btn_event"] = "📅 Post Event",
                ["btn_match"] = "⚔️ Post Match",
                ["btn_recruit"] = "🎮 Post Recruitment",
                ["success"] = "✅ Submitted – waiting for approval!",
                ["error_prefix"] = "❌ Error: ",
                ["conn_error"] = "❌ Connection error: ",
                ["fill_required"] = "Please fill all required fields (*)!",
                ["enter_opponent"] = "Please enter the opponent clan!",
                ["unknown_error"] = "Unknown error",
                ["update_available"] = "Update available",
                ["update_msg"] = "New version available: {0}\nCurrent version: {1}\n\nChangelog:\n{2}\n\nUpdate now?",
                ["no_update"] = "You already have the latest version!",
                ["no_update_title"] = "No Update",
                ["downloading"] = "Downloading update...",
                ["update_failed"] = "Update failed: ",
            },
            ["fr"] = new()
            {
                ["app_title"] = "Clan News Tool – Wolffiles.eu",
                ["login"] = "Connexion",
                ["logout"] = "Déconnexion",
                ["update"] = "🔄 Mise à jour",
                ["api_key"] = "Clé API :",
                ["api_key_hint"] = "Entrez la clé API...",
                ["connecting"] = "Connexion...",
                ["invalid_key"] = "Clé API invalide !",
                ["connection_error"] = "Connexion échouée !",
                ["enter_key"] = "Veuillez entrer votre clé API !",
                ["subtitle"] = "Wolffiles.eu – Portail Clan",
                ["tab_news"] = "📰 Actualités",
                ["tab_event"] = "📅 Événement",
                ["tab_match"] = "⚔️ Match",
                ["tab_recruit"] = "🎮 Recrutement",
                ["title"] = "Titre *",
                ["excerpt"] = "Résumé (optionnel)",
                ["content_news"] = "Contenu *",
                ["content_event"] = "Description *",
                ["content_match"] = "Rapport de match *",
                ["content_recruit"] = "Exigences & Détails *",
                ["event_date"] = "Date & Heure *",
                ["event_location"] = "Lieu / Serveur (optionnel)",
                ["opponent"] = "Clan adverse *",
                ["result"] = "Résultat (ex. 2:1)",
                ["map"] = "Carte (optionnel)",
                ["match_date"] = "Date du match",
                ["btn_news"] = "📰 Publier actualité",
                ["btn_event"] = "📅 Publier événement",
                ["btn_match"] = "⚔️ Publier match",
                ["btn_recruit"] = "🎮 Publier recrutement",
                ["success"] = "✅ Soumis – en attente d'approbation !",
                ["error_prefix"] = "❌ Erreur : ",
                ["conn_error"] = "❌ Erreur de connexion : ",
                ["fill_required"] = "Veuillez remplir tous les champs obligatoires (*) !",
                ["enter_opponent"] = "Veuillez entrer le clan adverse !",
                ["unknown_error"] = "Erreur inconnue",
                ["update_available"] = "Mise à jour disponible",
                ["update_msg"] = "Nouvelle version disponible : {0}\nVersion actuelle : {1}\n\nChangements :\n{2}\n\nMettre à jour ?",
                ["no_update"] = "Vous avez déjà la dernière version !",
                ["no_update_title"] = "Pas de mise à jour",
                ["downloading"] = "Téléchargement de la mise à jour...",
                ["update_failed"] = "Mise à jour échouée : ",
            },
            ["nl"] = new()
            {
                ["app_title"] = "Clan News Tool – Wolffiles.eu",
                ["login"] = "Inloggen",
                ["logout"] = "Uitloggen",
                ["update"] = "🔄 Update",
                ["api_key"] = "API-sleutel:",
                ["api_key_hint"] = "Voer API-sleutel in...",
                ["connecting"] = "Verbinden...",
                ["invalid_key"] = "Ongeldige API-sleutel!",
                ["connection_error"] = "Verbinding mislukt!",
                ["enter_key"] = "Voer uw API-sleutel in!",
                ["subtitle"] = "Wolffiles.eu – Clan Portaal",
                ["tab_news"] = "📰 Nieuws",
                ["tab_event"] = "📅 Evenement",
                ["tab_match"] = "⚔️ Match",
                ["tab_recruit"] = "🎮 Werving",
                ["title"] = "Titel *",
                ["excerpt"] = "Korte beschrijving (optioneel)",
                ["content_news"] = "Inhoud *",
                ["content_event"] = "Beschrijving *",
                ["content_match"] = "Matchverslag *",
                ["content_recruit"] = "Vereisten & Details *",
                ["event_date"] = "Datum & Tijd *",
                ["event_location"] = "Locatie / Server (optioneel)",
                ["opponent"] = "Tegenstander Clan *",
                ["result"] = "Resultaat (bijv. 2:1)",
                ["map"] = "Kaart (optioneel)",
                ["match_date"] = "Matchdatum",
                ["btn_news"] = "📰 Nieuws plaatsen",
                ["btn_event"] = "📅 Evenement plaatsen",
                ["btn_match"] = "⚔️ Match plaatsen",
                ["btn_recruit"] = "🎮 Werving plaatsen",
                ["success"] = "✅ Ingediend – wacht op goedkeuring!",
                ["error_prefix"] = "❌ Fout: ",
                ["conn_error"] = "❌ Verbindingsfout: ",
                ["fill_required"] = "Vul alle verplichte velden (*) in!",
                ["enter_opponent"] = "Voer de tegenstander clan in!",
                ["unknown_error"] = "Onbekende fout",
                ["update_available"] = "Update beschikbaar",
                ["update_msg"] = "Nieuwe versie beschikbaar: {0}\nHuidige versie: {1}\n\nWijzigingen:\n{2}\n\nNu updaten?",
                ["no_update"] = "U heeft al de nieuwste versie!",
                ["no_update_title"] = "Geen update",
                ["downloading"] = "Update downloaden...",
                ["update_failed"] = "Update mislukt: ",
            },
            ["pl"] = new()
            {
                ["app_title"] = "Clan News Tool – Wolffiles.eu",
                ["login"] = "Zaloguj się",
                ["logout"] = "Wyloguj się",
                ["update"] = "🔄 Aktualizacja",
                ["api_key"] = "Klucz API:",
                ["api_key_hint"] = "Wprowadź klucz API...",
                ["connecting"] = "Łączenie...",
                ["invalid_key"] = "Nieprawidłowy klucz API!",
                ["connection_error"] = "Połączenie nieudane!",
                ["enter_key"] = "Wprowadź swój klucz API!",
                ["subtitle"] = "Wolffiles.eu – Portal Klanu",
                ["tab_news"] = "📰 Aktualności",
                ["tab_event"] = "📅 Wydarzenie",
                ["tab_match"] = "⚔️ Mecz",
                ["tab_recruit"] = "🎮 Rekrutacja",
                ["title"] = "Tytuł *",
                ["excerpt"] = "Krótki opis (opcjonalnie)",
                ["content_news"] = "Treść *",
                ["content_event"] = "Opis *",
                ["content_match"] = "Raport z meczu *",
                ["content_recruit"] = "Wymagania i szczegóły *",
                ["event_date"] = "Data i godzina *",
                ["event_location"] = "Miejsce / Serwer (opcjonalnie)",
                ["opponent"] = "Klan przeciwnika *",
                ["result"] = "Wynik (np. 2:1)",
                ["map"] = "Mapa (opcjonalnie)",
                ["match_date"] = "Data meczu",
                ["btn_news"] = "📰 Opublikuj aktualność",
                ["btn_event"] = "📅 Opublikuj wydarzenie",
                ["btn_match"] = "⚔️ Opublikuj mecz",
                ["btn_recruit"] = "🎮 Opublikuj rekrutację",
                ["success"] = "✅ Wysłano – oczekuje na zatwierdzenie!",
                ["error_prefix"] = "❌ Błąd: ",
                ["conn_error"] = "❌ Błąd połączenia: ",
                ["fill_required"] = "Wypełnij wszystkie wymagane pola (*)!",
                ["enter_opponent"] = "Wprowadź klan przeciwnika!",
                ["unknown_error"] = "Nieznany błąd",
                ["update_available"] = "Dostępna aktualizacja",
                ["update_msg"] = "Dostępna nowa wersja: {0}\nAktualna wersja: {1}\n\nZmiany:\n{2}\n\nAktualizować teraz?",
                ["no_update"] = "Masz już najnowszą wersję!",
                ["no_update_title"] = "Brak aktualizacji",
                ["downloading"] = "Pobieranie aktualizacji...",
                ["update_failed"] = "Aktualizacja nieudana: ",
            },
            ["tr"] = new()
            {
                ["app_title"] = "Clan News Tool – Wolffiles.eu",
                ["login"] = "Giriş Yap",
                ["logout"] = "Çıkış Yap",
                ["update"] = "🔄 Güncelle",
                ["api_key"] = "API Anahtarı:",
                ["api_key_hint"] = "API Anahtarı girin...",
                ["connecting"] = "Bağlanıyor...",
                ["invalid_key"] = "Geçersiz API Anahtarı!",
                ["connection_error"] = "Bağlantı başarısız!",
                ["enter_key"] = "Lütfen API Anahtarınızı girin!",
                ["subtitle"] = "Wolffiles.eu – Klan Portalı",
                ["tab_news"] = "📰 Haberler",
                ["tab_event"] = "📅 Etkinlik",
                ["tab_match"] = "⚔️ Maç",
                ["tab_recruit"] = "🎮 Üye Alımı",
                ["title"] = "Başlık *",
                ["excerpt"] = "Kısa açıklama (isteğe bağlı)",
                ["content_news"] = "İçerik *",
                ["content_event"] = "Açıklama *",
                ["content_match"] = "Maç Raporu *",
                ["content_recruit"] = "Gereksinimler & Detaylar *",
                ["event_date"] = "Tarih & Saat *",
                ["event_location"] = "Konum / Sunucu (isteğe bağlı)",
                ["opponent"] = "Rakip Klan *",
                ["result"] = "Sonuç (örn. 2:1)",
                ["map"] = "Harita (isteğe bağlı)",
                ["match_date"] = "Maç Tarihi",
                ["btn_news"] = "📰 Haber Gönder",
                ["btn_event"] = "📅 Etkinlik Gönder",
                ["btn_match"] = "⚔️ Maç Gönder",
                ["btn_recruit"] = "🎮 Üye Alımı Gönder",
                ["success"] = "✅ Gönderildi – onay bekleniyor!",
                ["error_prefix"] = "❌ Hata: ",
                ["conn_error"] = "❌ Bağlantı hatası: ",
                ["fill_required"] = "Lütfen tüm zorunlu alanları (*) doldurun!",
                ["enter_opponent"] = "Lütfen rakip klanı girin!",
                ["unknown_error"] = "Bilinmeyen hata",
                ["update_available"] = "Güncelleme mevcut",
                ["update_msg"] = "Yeni sürüm mevcut: {0}\nMevcut sürüm: {1}\n\nDeğişiklikler:\n{2}\n\nŞimdi güncellensin mi?",
                ["no_update"] = "Zaten en son sürüme sahipsiniz!",
                ["no_update_title"] = "Güncelleme yok",
                ["downloading"] = "Güncelleme indiriliyor...",
                ["update_failed"] = "Güncelleme başarısız: ",
            },
        };

        public static void Initialize()
        {
            var culture = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLower();
            var supported = new[] { "de", "en", "fr", "nl", "pl", "tr" };
            CurrentLanguage = supported.Contains(culture) ? culture : "en";
            _strings = _translations.ContainsKey(CurrentLanguage)
                ? _translations[CurrentLanguage]
                : _translations["en"];
        }

        public static string Get(string key) =>
            _strings.TryGetValue(key, out var val) ? val : key;

        public static string T(string key) => Get(key);
    }
}